### PR TITLE
WIP feat(readonly): allow for readonly version of the webapp

### LINKED ISSUE #265: Make READ_ONLY version of the qri frontend
The READ_ONLY version of the qri frontend does not need:
* [x] the side bar => this will immediately get rid of a bunch of unneeded functionality
* [x] write inline read_only component that takes string name and link pairs from a config file and uses them to populate the page header
* [x] replace page header add/delete/export with this component
* [x] write block read_only component that displays a messages (taken from a config file) that displays when you need an alternative component
* [x] replace Data on dataset page with this component

However, the major issue is going to be figuring out a bug that messes up the app when you refresh a page, or try to access a page by typing it into the html bar

Also, issue #264 and qri-io/qri#310 really need to be closed before we can get super far on this, since that bug makes being on the dataset page really unpleasant

### PR DESCRIPTION
**Pull request by ramfox**

### CODE REVIEW

**Comment by b5** [comment]
I'm assuming this is abandoned. Can we close this @ramfox?

**Comment by ramfox** [comment]
Yea, I'm about to start on the qri readonly, and then swing back to the frontend readonly. Not sure if I can use this branch and -f an update, or if it's better to close and delete the branch and start new.

Whichevs you think is best!

**Comment by b5** [comment]
meh let's leave it open until we know for sure it's not going to be useful 😄

**Comment by ramfox** [comment]
Now that #265 has been closed by #274, closing this pr

**Pull request closed without merging**
