### PR TITLE
feat(reducers): add tests to reducers 

### LINKED ISSUE #213: Add tests to reducers
Using jest and redux-testkit, add tests to the reducers: settings, session, locals, layout, console, app

### PR DESCRIPTION
**Pull request by ramfox**
closes #213 

* [x] settings
* [x] session
* [x] locals
* [x] layout
* [x] console
* [x] app

### CODE REVIEW

**Comment by ramfox** [comment]
Okay so yes session and settings are pretty much redundant. Adding issue to refactor to remove all references to settings, and to use session instead.

**Review by b5 — APPROVED** [review]
🐖 🦆 ⛵️

**Comment by ramfox** [comment]
So all the reducers, except for index, paginate, and pagination, have tests!

Just want to make sure that this is still approved before I merge it `:)`

**Comment by b5** [comment]
Looks great! Glad to see some dead code elimination from some of these actions. let's merge!

**Pull request merged**
