### PR TITLE
Adding documentation to repo

### PR DESCRIPTION
**Pull request by ramfox**
Using the cafs, hyper, and angular.js docs as a model, adding documentation to our frontend repo!

### CODE REVIEW

**Comment by b5** [comment]
closes #117

**Comment by ramfox** [comment]
Do folks have to 'sign' a CLA before contributing??

**Comment by b5** [comment]
Yeah they'll need to, we should create an issue for that process. For now let's add a note to the documentation that we'll be asking contributors to sign a CLA before we can merge their PR's.

**Comment by ramfox** [comment]
Got it

**Review by b5 — APPROVED** [review]
👍 🥇 💯

**Pull request merged**
